import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const onSubmit = (e) => {
    e.preventDefault();
  };
  return (
    <>
      <Head>
        <title>New Book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h2>Add Book</h2>
          <div>
            <form onSubmit={onSubmit}>
              <br />
              <input type="text" name="title" placeholder="Title" />
              <br />
              <input type="text" name="author" placeholder="Author" />
              <br />
              <button type="submit">Submit</button>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
